# Generated by Django 3.2.9 on 2021-12-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_alter_question_qimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='qno',
            new_name='num',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='qtext',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='questionpapers',
            old_name='qpid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='questionpapers',
            old_name='qpno',
            new_name='num',
        ),
        migrations.RemoveField(
            model_name='question',
            name='qimg',
        ),
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/ques/'),
        ),
        migrations.AddField(
            model_name='questionpapers',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/quespaper/'),
        ),
        migrations.AddField(
            model_name='questionpapers',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
