# Generated by Django 3.2.9 on 2021-12-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20211202_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='set_name',
        ),
    ]
