# Generated by Django 3.2.9 on 2021-12-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_remove_question_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='set_name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
    ]
