# Generated by Django 3.2.9 on 2021-12-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_alter_question_qpid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpapers',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/static/quespaper/'),
        ),
    ]
