# Generated by Django 3.2.9 on 2021-12-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_alter_questionpapers_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpapers',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/quespaper/'),
        ),
    ]
